CREATE TABLE IF NOT EXISTS pricing_plans (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  price VARCHAR(50) NOT NULL,
  description TEXT,
  features JSONB,
  timeline VARCHAR(50),
  is_popular BOOLEAN DEFAULT FALSE,
  button_text VARCHAR(50) DEFAULT 'Choose Plan'
);

CREATE TABLE IF NOT EXISTS portfolio_works (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  category VARCHAR(50) NOT NULL,
  summary TEXT,
  stack JSONB,
  image_url TEXT NOT NULL,
  link TEXT,
  tag VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS service_offerings (
  slug VARCHAR(80) PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  summary TEXT NOT NULL,
  description TEXT NOT NULL,
  starting_at VARCHAR(80) NOT NULL,
  timeline VARCHAR(80) NOT NULL,
  support TEXT NOT NULL,
  includes JSONB NOT NULL DEFAULT '[]'::jsonb,
  best_for JSONB NOT NULL DEFAULT '[]'::jsonb,
  optional_extras JSONB NOT NULL DEFAULT '[]'::jsonb,
  faqs JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE TABLE IF NOT EXISTS site_faqs (
  id SERIAL PRIMARY KEY,
  category VARCHAR(80) NOT NULL,
  question TEXT NOT NULL,
  answer TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS testimonials (
  id SERIAL PRIMARY KEY,
  client_name VARCHAR(100) NOT NULL,
  company VARCHAR(100),
  feedback TEXT NOT NULL,
  rating INTEGER DEFAULT 5,
  avatar_url TEXT
);

CREATE TABLE IF NOT EXISTS blog_posts (
  id SERIAL PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  excerpt TEXT NOT NULL,
  date DATE NOT NULL,
  image_url TEXT,
  link TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contacts (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  phone VARCHAR(50),
  service VARCHAR(100),
  budget VARCHAR(100),
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_sessions (
  id VARCHAR(100) PRIMARY KEY,
  last_user_message TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_messages (
  id BIGSERIAL PRIMARY KEY,
  session_id VARCHAR(100) NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
  role VARCHAR(20) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE pricing_plans ADD COLUMN IF NOT EXISTS timeline VARCHAR(50);
ALTER TABLE portfolio_works ADD COLUMN IF NOT EXISTS summary TEXT;
ALTER TABLE portfolio_works ADD COLUMN IF NOT EXISTS stack JSONB;
ALTER TABLE portfolio_works ADD COLUMN IF NOT EXISTS tag VARCHAR(80);
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS service VARCHAR(100);
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS budget VARCHAR(100);
